// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "fd4aaf18-fe8b-4da9-a432-1998d235e452";

const char SSID[]               = "RAJPUT";    // Network SSID (name)
const char PASS[]               = "GOVIND789";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "LML0UCB4HSS9FRMWJ1C7";    // Secret device password


CloudElectricCurrent eC;
float pH;
int tDS;
CloudTemperature temperature;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(eC, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pH, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tDS, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
